meta_product_name: "Mumamigas"
meta_title: "Mumamigas - Meet other mums"
meta_description: "Connect with othet mums"
meta_image: "background.jpg"                       # should exist in `app/assets/images/`

